import img9mm from "@/shared/assets/productsImages/9mm.webp";
import img12ga from "@/shared/assets/productsImages/12ga.webp";
import img223 from "@/shared/assets/productsImages/223.webp";
import img308 from "@/shared/assets/productsImages/308win.webp";

export const mockProducts = [
  {
    slug: "p-308",
    title: ".308 WINCHESTER",
    subtitle: "Dry Fire Training",
    image: img308,
    category: "rifles",
    popular: 98,
    price: 49,
    isNew: true,
    tag: "MOST POPULAR",
    amazonUrl: "",
  },
  {
    slug: "p-223",
    title: ".223 REMINGTON",
    subtitle: "AR-15 Compatible",
    image: img223,
    category: "ar",
    popular: 92,
    price: 39,
    isNew: true,
    amazonUrl: "",
  },
  {
    slug: "p-9mm",
    title: "9mm LUGER",
    subtitle: "Handgun Training",
    image: img9mm,
    category: "handgun",
    popular: 95,
    price: 35,
    isNew: true,
    amazonUrl: "https://www.amazon.com/stores/page/B8F49A19-43C9-4131-B1DE-280B6AFB8E6F?ingress=2&lp_context_asin=B0FVFSF2WG&visitId=8faa0f3b-ba5a-42d6-a310-415800921076&ref_=ast_bln",
  },
  {
    slug: "p-12ga",
    title: "12 GAUGE",
    subtitle: "Shotgun Dummy Rounds",
    image: img12ga,
    category: "rifles",
    popular: 74,
    price: 31,
    isNew: false,
    amazonUrl: "",
  },

  {
    slug: "p-40sw-a",
    title: ".40 S&W",
    subtitle: "Pistol Snap Caps",
    image: img9mm,
    category: "handgun",
    popular: 78,
    price: 27,
    isNew: false,
    amazonUrl: "",
  },
  {
    slug: "p-45acp-a",
    title: ".45 ACP",
    subtitle: "Dry Fire Training",
    image: img12ga,
    category: "handgun",
    popular: 88,
    price: 33,
    isNew: false,
    amazonUrl: "",
  },
  {
    slug: "p-12ga-a",
    title: "12 GAUGE",
    subtitle: "Shotgun Dummy Rounds",
    image: img12ga,
    category: "rifles",
    popular: 74,
    price: 31,
    isNew: false,
    amazonUrl: "",
  },
  {
    slug: "p-357",
    title: ".357 MAGNUM",
    subtitle: "Revolver Basics",
    image: img308,
    category: "revolver",
    popular: 80,
    price: 32,
    isNew: false,
    amazonUrl: "",
  },

  {
    slug: "p-40sw-b",
    title: ".40 S&W",
    subtitle: "Pistol Snap Caps",
    image: img223,
    category: "handgun",
    popular: 70,
    price: 25,
    isNew: false,
    amazonUrl: "",
  },
  {
    slug: "p-45acp-b",
    title: ".45 ACP",
    subtitle: "Dry Fire Training",
    image: img308,
    category: "handgun",
    popular: 84,
    price: 34,
    isNew: false,
    amazonUrl: "",
  },
  {
    slug: "p-12ga-b",
    title: "12 GAUGE",
    subtitle: "Shotgun Dummy Rounds",
    image: img12ga,
    category: "rifles",
    popular: 73,
    price: 30,
    isNew: false,
    amazonUrl: "",
  },
  {
    slug: "p-ar-kit",
    title: "AR KIT",
    subtitle: "Platform Essentials",
    image: img223,
    category: "ar",
    popular: 86,
    price: 44,
    isNew: true,
    amazonUrl: "",
  },

  {
    slug: "p-rifle-kit",
    title: "RIFLE KIT",
    subtitle: "Practice Pack",
    image: img308,
    category: "rifles",
    popular: 77,
    price: 42,
    isNew: false,
    amazonUrl: "",
  },
  {
    slug: "p-handgun-kit",
    title: "HANDGUN KIT",
    subtitle: "Starter Bundle",
    image: img9mm,
    category: "handgun",
    popular: 90,
    price: 46,
    isNew: true,
    amazonUrl: "",
  },
];